### ISSUE TITLE
TypeError: Cannot read property 'split' of undefined

### ISSUE THREAD

**Issue by neillturner** [toshihirock/node-elb-log-parser#6]
getting these errors calling this npm from the code at 
https://github.com/prithviraju/aws-elb-logs-to-elasticsearch/blob/master/index.js 

TypeError: Cannot read property 'split' of undefined
at module.exports (/var/task/node_modules/elb-log-parser/index.js:69:45)
at Transform.recordStream._transform (/var/task/index.js:148:25)
at Transform._read (_stream_transform.js:186:10)
at Transform._write (_stream_transform.js:174:12)
at doWrite (_stream_writable.js:397:12)
at writeOrBuffer (_stream_writable.js:383:5)
at Transform.Writable.write (_stream_writable.js:290:11)
at LineStream.ondata (_stream_readable.js:639:20)
at emitOne (events.js:116:13)
at LineStream.emit (events.js:211:7)

happen on line: 
  parsed['backend_port'] = parsed.backend.split(":")[1];

**Comment by heyakim** [comment]
I'm having this issue on my deployment. Is there a fix for this already? Thanks.

**Comment by yan74** [comment]
I had this issue because I was feeding gzipped logs to the lambda. If your s3 bucket contains .gz objects you need to add 

```
const {createGunzip} = require('gunzip-stream');
...
    s3Stream
      .pipe(createGunzip())
      .pipe(lineStream)
      .pipe(recordStream)
```

**Comment by kartikeypokhriyal7000** [comment]
Was this issue fixed ? I'm still facing it

**Comment by neillturner** [comment]
there is a pull request 
TypeError: Cannot read property 'split' of undefined #6
